# Generated by Django 4.2.24 on 2026-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('quote', 'Quote Legendaris'), ('event', 'Kejadian Absurd'), ('meme', 'Meme Internal'), ('history', 'Sejarah BS')], max_length=20)),
                ('date_occurred', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_occurred', '-created_at'],
            },
        ),
    ]
