# Generated by Django 4.2.24 on 2026-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('mvp_sports', 'MVP Olahraga'), ('raja_mabar', 'Raja Mabar'), ('legend', 'Legend Tongkrongan'), ('chaotic', 'Most Chaotic Member'), ('talent', 'Talent Showcase')], max_length=20)),
                ('recipient', models.CharField(max_length=100)),
                ('date_achieved', models.DateField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
    ]
