# Generated by Django 4.2.24 on 2026-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('real_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('alumni', 'Alumni')], default='member', max_length=20)),
                ('skills', models.TextField(help_text='Separate with commas')),
                ('favorite_game', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('legend', 'Legend')], default='active', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, to='members.badge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
