# Generated by Django 4.2.24 on 2026-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='tiktok',
            field=models.CharField(blank=True, help_text='TikTok username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number (with country code)', max_length=20),
        ),
    ]
